### ISSUE TITLE
Replace geocode api with autocomplete

### ISSUE THREAD

**Issue by Haniyya** [lokalportal/feed-mapper#1]
https://github.com/lokalportal/feed-mapper/blob/04b2aa73d2ad12c6c26c6ecd21d7b1eda09efd9c/src/external-event.js#L80

Here we can probably use `.placesAutoComplete` instead of `.geocode` to save some bandwidth.

**Comment by stex** [comment]
I tested this (see https://github.com/lokalportal/feed-mapper/blob/master/src/external-event.js#L107), the results were worse than when using the Geocoder API. As I left the code in, we can check back from time to time, but I don't really think it's worth it for a cloud function.
